-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Mar 27, 2019 at 11:56 AM
-- Server version: 5.7.19
-- PHP Version: 7.1.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `am1b-loginregistration-2018`
--
CREATE DATABASE IF NOT EXISTS `am1b-loginregistration-2018` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `am1b-loginregistration-2018`;

-- --------------------------------------------------------

--
-- Table structure for table `login`
--

DROP TABLE IF EXISTS `login`;
CREATE TABLE IF NOT EXISTS `login` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` varchar(350) NOT NULL,
  `password` varchar(60) NOT NULL,
  `userrole` enum('administrator','customer','moderator','root') NOT NULL DEFAULT 'customer',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `description` varchar(600) NOT NULL,
  `imageUrl` varchar(500) NOT NULL,
  `catagory` enum('dames', 'heren') NOT NULL,
  `subcatagory` enum('schoenen', 'kleding', 'accessoires') NOT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `login`
--

INSERT INTO `login` (`id`, `email`, `password`, `userrole`) VALUES
(1, 'customer@gmail.com', '$2y$10$EWwqPA1AvSRXKkrJ8fOv5.M8wDFXqXLPtrbTOaOTDfPOKJsPNZ4Ve', 'customer'),
(2, 'admin@gmail.com', '$2y$10$fXbvSP0f6QnSRZJ.qAVxvOvfAqfsoHg57oywuqL0.PouqoLUXO6dK', 'administrator'),
(3, 'root@gmail.com', '$2y$10$5nbxombZYFneeKGX5BzvH.MbP04H43Lyi1P9mmAnf/7qP/oVTae5S', 'root'),
(4, 'moderator@gmail.com', '$2y$10$2pgAyVAEqCb6iTVaWAdHF.YAAVfMZUjZqQ9IIW5VcruzyMZkbJss.', 'moderator'),
(5, 'test@gmail.com', '$2y$10$lkyR./J7ApUkzu5wSN0Mge0m3PZ0XB/UW3ZLByudEq0/ybvu0P9ZG', 'customer');
COMMIT;

INSERT INTO `products` (`title`, `description`, `imageUrl`, `catagory`, `subcatagory`) VALUES
('Nike Air Max 270 React Bauhaus', 'De Nike Air Max 270 React is ge&iumlnspireerd op kleuren en texturen uit kunstbewegingen van de vorige eeuw en gebruikt lichte materialen in laagjes om een modern design te cre&eumlren dat er net zo goed uitziet als het aanvoelt.', 'https://c.static-nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/bfz2oeb4m1idr94ziqlh/air-max-270-react-herenschoen-jlGF96.jpg', 'heren', 'schoenen'),
('Nike Air Force 1 \'07', 'De legende leeft voort in de Nike Air Force 1 \'07, een moderne uitvoering van het icoon waarin klassieke stijl en moderne, frisse details samenkomen.', 'https://c.static-nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/gsuin11ptg5qgktmzoat/air-force-1-07-herenschoen-DS3Q3T.jpg', 'heren', 'schoenen'),
('NikeCourt Air Zoom Vapor X', 'Dankzij Nike Zoom Air en een Dynamic Fit systeem zorgt de NikeCourt Air Zoom Vapor X voor ultieme controle op hardcourts.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/swenes8jczpitkukvdeb/nikecourt-air-zoom-vapor-hardcourt-tennisschoen-heren-t7NRcJ.jpg', 'heren', 'schoenen'),
('Nike Epic React Flyknit 2', 'De Nike Epic React Flyknit 2 gaat een stap verder dan zijn voorganger met een licht gewicht, soepele performance en een opvallende look. Een verbeterd Flyknit bovenwerk vormt zich naar je voet en heeft een minimalistisch, ondersteunend design. Duurzame Nike React technologie onder de voet doet het onmogelijke. Het is zacht en responsief voor comfort tijdens je hele run.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/oon1z2gcoxerwh6orxr9/epic-react-flyknit-2-hardloopschoen-heren-6jWxP5.jpg', 'heren', 'schoenen'),
('Nike Shox R4', 'De Nike Shox R4 biedt de ultieme responsieve demping met 4 ondersteunende kolommen onder de hiel. Het lichte bovenwerk van synthetisch materiaal en textiel is zacht en duurzaam. Perforaties bij de tenen en rond de enkel verbeteren de ventilatie.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ndlaclu32zzdfzrckric/shox-r4-herenschoen-j9QKgK.jpg', 'heren', 'schoenen'),
('Nike SB Zoom Stefan Janoski RM', 'De Nike SB Zoom Stefan Janoski RM combineert een minimalistische look met een moderne pasvorm. De schoen is vernieuwd met een nieuwe, zachte inlegzool en een flexibele buitenzool voor een betere boardfeel vanaf het eerste gebruik.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/z7lpybmgujcskghcy16q/sb-zoom-stefan-janoski-rm-skateschoen-wrdqPL.jpg', 'heren', 'schoenen'),
('Nike SB Chron Solarsoft', 'De Nike SB Chron Solarsoft combineert zacht suède met flexibel canvas voor premium performance. Met een inlegzool van foam met twee dichtheden die je voeten steun geeft tijdens het skaten en demping biedt bij grote drops en tricks.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/mt99kz7kvadm8vhqgqxh/sb-chron-solarsoft-skateschoen-4l5zH1.jpg', 'heren', 'schoenen'),
('Nike Air Vortex', 'De Nike Air Vortex herenschoen blijft trouw aan het origineel uit de jaren 80 en biedt stabiliteit en zachte demping.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/hj4f1f8wvqoxbkzs8quy/air-vortex-herenschoen-7C1K5c.jpg', 'heren', 'schoenen'),
('Nike Air Max 97', 'De Nike Air Max 97 herenschoen zorgt ervoor dat de sneakerfavoriet populair blijft met dezelfde designkenmerken waardoor de schoen beroemd werd: lijnen in de vorm van waterrimpels, reflecterende biezen en Max Air demping over de volle lengte.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/wxgzqes4vmhricwvocgf/air-max-97-herenschoen-Sv1PBG.jpg', 'heren', 'schoenen'),
('Nike SFB Field 2', 'De Nike SFB Field 2 20 cm boots zijn lichte, hoogwaardige boots die zijn ontworpen om op alle terreinen ondersteuning te bieden bij zware ladingen. De zool heeft een robuust profiel dat zorgt voor uitzonderlijke grip op uitdagend terrein en de speciale binnenlaag voorkomt dat er gaten ontstaan.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/fn9riigqtlwxojjv0yuv/sfb-field-2-20-cm-boots-swmcN2.jpg', 'heren', 'schoenen'),
('Air Jordan 1 Mid', 'De Air Jordan 1 Mid biedt een sportieve stijl en premium comfort voor een iconische look. De Air-Sole unit zorgt voor demping op de hardhouten ondergrond, terwijl de gewatteerde kraag voor ondersteuning zorgt.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/c3q2hhmglebgohuh7teh/air-jordan-1-mid-damesschoen-X2vlhw.jpg', 'dames', 'schoenen'),
('Nike Air Force 1 \'07', 'De legende leeft voort in de Nike Air Force 1 \'07, een moderne uitvoering van het icoon waarin klassieke stijl en moderne, frisse details samenkomen.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/acxwowgwxpyawi3ylaqy/air-force-1-07-damesschoen-sg6nmr.jpg', 'dames', 'schoenen'),
('Nike Air Max 270 React', 'De Nike Air Max 270 React is ge&iumlnspireerd op kleuren en texturen uit kunstbewegingen van de vorige eeuw en gebruikt lichte materialen in laagjes om een modern design te cre&eumlren dat er net zo goed uitziet als het aanvoelt.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/nex5fgeecvdhjrmbiiyl/air-max-270-react-damesschoen-GtQwwb.jpg', 'dames', 'schoenen'),
('Nike Zoom 2K', 'De Nike Zoom 2K is geïnspireerd op de vibe van begin jaren 2000 en combineert een klassieke stijl met het moderne comfort van Zoom Air demping. De materiaalmix op het bovenwerk wordt benadrukt door rubberen \'vleugels\' die de buitenzool aan beide zijkanten omsluiten. Dit zorgt voor een opvallende look die zowel vintage als futuristisch is.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/wtlawuwa4xi9ase8umex/zoom-2k-damesschoen-XtKZHq.jpg', 'dames', 'schoenen'),
('Nike Air Max Plus Metallic', 'De Nike Air Max Plus Metallic damesschoen heeft Tuned Air voor de juiste demping waar je die nodig hebt. Deze Air Max Plus verscheen in 1998 en werd al snel een icoon dankzij de voorgevormde overlays en het opvallende silhouet.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/gvdaqvcvmvzokrrgrcem/air-max-plus-metallic-damesschoen-P0NCTF.jpg', 'dames', 'schoenen'),
('Nike SB Zoom Stefan Janoski RM', 'De Nike SB Zoom Stefan Janoski RM combineert een minimalistische look met een moderne pasvorm. De schoen is vernieuwd met een nieuwe, zachte inlegzool en een flexibele buitenzool voor een betere boardfeel vanaf het eerste gebruik.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/z7lpybmgujcskghcy16q/sb-zoom-stefan-janoski-rm-skateschoen-wrdqPL.jpg', 'dames', 'schoenen'),
('Nike Air VaporMax Flyknit 3', 'Ervaar de veerkracht van de Nike Air VaporMax Flyknit 3. Het bovenwerk van ventilerend en rekbaar Flyknit materiaal is geïnspireerd op high fashion met vloeiende lijnen. Revolutionaire VaporMax Air technologie geeft je pas veerkracht met demping van teen tot hak.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/f3y2mkckqmmgl60gkue5/air-vapormax-flyknit-3-damesschoen-CLkhvH.jpg', 'dames', 'schoenen'),
('Nike Legend React', 'De Nike Legend React hardloopschoen voor dames is gemaakt van ademend bovenwerk met synthetische lagen voor meer duurzaamheid terwijl zacht, responsief foam elke stap dempt tijdens je run.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/dvi1ymgvcujnyd5tahut/legend-react-hardloopschoen-dames-lM0gxR.jpg', 'dames', 'schoenen'),
('Nike Classic Cortez Nylon', 'De Nike Classic Cortez Nylon damesschoen is de eerste hardloopschoen van Nike, ontworpen door Bill Bowerman en geïntroduceerd in 1972. Deze versie heeft een nylon bovenwerk met suède overlays voor een licht gevoel en een retrostijl.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ijmu8fpgpou76q2yttqn/classic-cortez-nylon-damesschoen-olTW9wzX.jpg', 'dames', 'schoenen'),
('NikeCourt Air Max Wildcard', 'De NikeCourt Air Max Wildcard biedt het comfort dat je nodig hebt om hard te slaan en snel te bewegen op de baan. Een Max Air unit biedt demping bij elke stap, terwijl een innovatieve Lunarlon middenzool zorgt voor een veerkrachtig gevoel en extra stabiliteit.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/kras4d07wsaknkxoz8fc/nikecourt-air-max-wildcard-tennisschoen-dames-2mTJ5N.jpg', 'dames', 'schoenen'),
('Nike Sportswear Tech Fleece', 'De Nike Sportswear Tech Fleece Jogger herenbroek heeft een toelopende pasvorm die is gemaakt om in te bewegen. De broek heeft meerdere zakken en licht en ademend materiaal.', 'https://c.static-nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/kjcvnl4wag9ovv4mooql/sportswear-tech-fleece-joggingbroek-heren-ZWtrVv.jpg', 'heren', 'kleding'),
('Nike Sportswear Tech Fleece', 'De Nike Sportswear Tech Fleece hoodie vernieuwt een klassieker en houdt je warm dankzij het lichte Nike Tech Fleece materiaal. Deze moderne uitvoering van de klassieke hoodie heeft een ritssluiting in twee richtingen.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ekseonooxsjdmojqtrnl/sportswear-tech-fleece-hoodie-met-rits-heren-D1btrt.jpg', 'heren', 'kleding'),
('Nike Sportswear Air Max', 'De Nike Sportswear Air Max hoodie is klaar voor zijn debuut op straat. De handige zakken, het design met halflange ritssluiting en een uniek trekkoord met stopper bij de capuchon zorgen voor een look die trouw blijft aan de legende.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ykbz1aeedh7pf50ez2ej/sportswear-air-max-hoodie-met-halflange-rits-heren-h9nD5z.jpg', 'heren', 'kleding'),
('Nike Pro', 'De Nike Pro broek geeft je veelzijdig comfort tijdens je training. Het lichte, zweetafvoerende materiaal heeft een slank design en ritsjes bij de enkels en is dus ideaal om op zichzelf of als laagje te dragen.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/aktex4dnbwpfeaofnnrb/pro-herenbroek-PLbb5j.jpg', 'heren', 'kleding'),
('Nike Pro AeroAdapt', 'De Nike Pro AeroAdapt top biedt gerichte ventilatie die is aangepast aan jouw performance. De vochtgevoelige splitjes zorgen voor meer luchtcirculatie wanneer dat nodig is. Het lichte materiaal droogt snel zodat er geen zweetplekken ontstaan en je nog zelfverzekerder wordt.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/hf9svqgmhvcm4xnlqvfv/pro-aeroadapt-herentop-met-korte-mouwen-CLkpr0.jpg', 'heren', 'kleding'),
('Nike Pro Flex Rep', 'De Nike Sportswear Tech Fleece hoodie vernieuwt een klassieker en houdt je warm dankzij het lichte Nike Tech Fleece materiaal. Deze moderne uitvoering van de klassieke hoodie heeft een ritssluiting in twee richtingen.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ekseonooxsjdmojqtrnl/sportswear-tech-fleece-hoodie-met-rits-heren-D1btrt.jpg', 'heren', 'kleding'),
('Giannis Nike Dri-FIT \'Freak\'', 'Ga helemaal los in het Giannis Nike Dri-FIT T-shirt met een groot \'FREAK\' Swoosh design dat is geïnspireerd door de Griekse freak zelf, Giannis Antetokounmpo.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/afhzph7ug7ukanqzwza1/giannis-dri-fit-freak-basketbalshirt-heren-MGXtFm.jpg', 'heren', 'kleding'),
('NikeCourt Slam', 'Het NikeCourt Slam jack is een klassiek bomberjack met de look van een tennisjack met premium materialen waarmee je je look naar een hoger niveau tilt. Het omkeerbare design heeft verwijderbare patches zodat je je stijl op en buiten het veld kunt aanpassen.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/kmmd6j1o3u08rzepupks/nikecourt-slam-omkeerbaar-tennisjack-PRsZGV.jpg', 'heren', 'kleding'),
('Paris Saint-Germain', 'De Paris Saint-Germain hoodie verenigt erfgoed van Jordan met de Franse voetbalclub voor een must-have voor de straat. Deze trui met zacht geborsteld fleecemateriaal voor een comfortabel, relaxt gevoel heeft hoodiedetails, een kangoeroezak en clubafbeeldingen waarmee je laat zien dat je trots bent op je team.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ibdtdxdffkdhdsdjvmmd/paris-saint-germain-fleecehoodie-heren-lHl21k.jpg', 'heren', 'kleding'),
('Giannis \'Freak\'', 'Blijf Freaky in de Giannis \'Freak\' hoodie, een hoodie die is gemaakt voor levende legende Giannis Antetokounmpo. De hoodie is gemaakt van premium sweatstof en deze relaxte, gemakkelijke laag past bijna overal bij.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/fga3bcwuuf8glro0lhgw/giannis-freak-basketbalhoodie-heren-Dwbhz0.jpg', 'heren', 'kleding'),
('Nike Sportswear Windrunner Tech Fleece', 'De Nike Sportswear Windrunner Tech Fleece hoodie met rits voor dames is een nieuwe versie van een iconisch design en houdt je warm dankzij het lichte Nike Tech Fleece materiaal. De hoodie heeft een klassiek v-vormig design dat is geïnspireerd op het originele Windrunner jack.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/wllsaib74qfjeqcw4vvw/sportswear-windrunner-tech-fleece-hoodie-met-rits-dames-81d72F.jpg', 'dames', 'kleding'),
('Nike F.C. Dri-FIT', 'De Nike F.C. Dri-FIT top heeft een omkeerbaar design waarmee je je look kunt afwisselen. Beide kanten hebben een subtiel mat-glimmend patroon met de tekst \'Nike Football\' in verschillende talen op de voorkant. Dri-FIT technologie houdt je droog en comfortabel. De kortere pasvorm eindigt bij je heupen.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/q8pfnasac7mxst2e63ag/fc-dri-fit-voetbaltop-met-korte-mouwen-dames-sTZ2Sc.jpg', 'dames', 'kleding'),
('Nike F.C. Dri-FIT', 'De Nike F.C. Dri-FIT hoodie is zacht, comfortabel en zweetafvoerend en biedt echte voetbalstijl, zowel op straat als op het veld.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/zaollppz1qqz0nfcykvv/fc-dri-fit-voetbalhoodie-met-halflange-rits-dames-rbL3lw.jpg', 'dames', 'kleding'),
('Sleek, High-Rise Joggers', 'De Nike Sportswear Tech Fleece damesbroek is een technische update van klassieke joggingbroeken. Deze broek houdt je warm en is erg flatterend dankzij het design met hoge taille.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/yua9eyzu7xvvrxlhxkpr/sportswear-tech-fleece-damesbroek-THrxv2.jpg', 'dames', 'kleding'),
('Nike Sportswear Windrunner', 'Ga in alle weersomstandigheden naar buiten in het Nike Sportswear Windrunner jack met lichte isolatie en iconisch chevrondesign. De capuchon beschermt je tegen de kou tijdens je avonturen.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/fa4tzqj5ustw02z5fuxl/sportswear-windrunner-damesjack-met-capuchon-8Xcb3P.jpg', 'dames', 'kleding'),
('Hurley Modernist Zip', 'De Hurley Modernist Zip overall zorgt voor een strakke pasvorm en is gemaakt van zacht katoen. Een flatteuze lage rug en verstelbare bandjes zorgen voor comfort en stijl op maat.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/leoaybofvpopizvidlkr/hurley-modernist-zip-overall-dames-s2MMH7.jpg', 'dames', 'kleding'),
('Tottenham Hotspur', 'Laat zien dat je trots bent op je team met het Tottenham Hotspur T-shirt. Zacht katoen dat de hele dag lekker zit.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/kmjch6at6dttuqk59qrm/tottenham-hotspur-t-shirt-dames-52bxxt.jpg', 'dames', 'kleding'),
('Nike Dri-FIT UV', 'De Nike Dri-FIT UV polo is gemaakt van flexibel, zweetafvoerend materiaal met een frisse print en is een essential voor op de baan. Knopen met imitatieparels zorgen voor een verfijnde stijl.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ivpxonebyk9n9l0aqj1d/dri-fit-uv-golfpolo-met-print-dames-LjGXxR.jpg', 'dames', 'kleding'),
('Nike', 'De Nike hardlooptop met korte mouwen voor dames is gemaakt voor je run; met ventilatieopeningen aan de zijkanten en zweetafvoerend materiaal voor ultiem comfort.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/etbsceiqn4mzr6ckxqym/hardlooptop-met-korte-mouwen-dames-kRP7lq.jpg', 'dames', 'kleding'),
('Nike Dri-FIT UV', 'Het Nike Dri-FIT UV jack is gemaakt met rekbaar, zweetafvoerend materiaal en zorgt voor extra warmte wanneer je die nodig hebt. Voorgevormde mouwboorden houden je handen warm zonder je grip in de weg te zitten.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/xlpdxd7lcoxjaprugfhq/dri-fit-uv-golfjack-dames-6SFHZm.jpg', 'dames', 'kleding'),
('Nike Explore', 'De Nike Explore rugzak heeft een bovenklep en ruime binnen- en buitenvakken. De onderkant met coating houdt vocht buiten en de verstelbare, gewatteerde schouderbanden zorgen voor aanpasbaar draaggemak. Het gestencilde \'NIKE\' draagt bij aan de camouflagelook.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/entpvrnw7syquoh1o0t4/explore-rugzak-met-print-WkvFRD.jpg', 'heren', 'accessoires'),
('Nike Heritage', 'Met de Nike Heritage heuptas heb je gemakkelijk toegang tot je spullen wanneer je onderweg bent. Hij heeft een verstelbare band voor comfort op maat.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/mblh8rl8e5xbxqjavwsq/heritage-heuptas-cmgVGr.jpg', 'heren', 'accessoires'),
('Nike Terminus Mirrored', 'De stevige, handige Nike Terminus Mirrored zonnebril blijft goed zitten en biedt helder zicht tijdens intensieve trainingen of wedstrijden.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ygdria57ucjhquw9a8mb/terminus-mirrored-zonnebril-2pj7TQ.jpg', 'heren', 'accessoires'),
('Nike Radiate', 'De Nike Radiate rugzak heeft een bovenklep en meerdere vakken om spullen veilig in op te bergen. Een laptopsleeve beschermt je apparaat en een voorvak met laserperforaties zorgt voor een goed geventileerde opslag.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/bw3lbrz1bcupp2vs5y7h/radiate-rugzak-0BBHbh.jpg', 'heren', 'accessoires'),
('Nike Air Pro', 'De comfortabele Nike Air Pro pet heeft een design met 6 vlakken, een klassieke klep en een verstelbare sluiting aan de achterkant. Gemaakt van duurzame, lichte tafzijde die voor ondersteuning zorgt.', 'https://c.static-nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/oycyjvqrmyafinxfkpan/air-pro-verstelbare-pet-RbdZbb.jpg', 'heren', 'accessoires'),
('Nike Sportswear RPM', 'In de Nike Sportswear RPM rugzak kun je al je spullen opbergen. Hij heeft ook meerdere veilige ritsvakken. De rugzak heeft een gevoerde achterkant en veelzijdige bandjes — comfortabel en perfect voor onderweg.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/odgfld9kpahka6ccmgav/sportswear-rpm-rugzak-heren-cRJT1N.jpg', 'heren', 'accessoires'),
('Nike Legacy91 Tottenham Hotspur', 'De lichte en ademende Nike Legacy91 Tottenham Hotspur pet is gemaakt van zweetafvoerend materiaal en houdt je droog en comfortabel, zodat je je op het spel kunt concentreren.', 'https://c.static-nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/nfdhq1b9qntexh15lxzd/legacy91-tottenham-hotspur-pet-sczCZ0.jpg', 'heren', 'accessoires'),
('Jordan Velocity', 'De Jordan Velocity rugzak heeft meer dan genoeg opbergmogelijkheden, waaronder een intern ritsvak voor je toiletspullen, een zijvak en een compartiment met rits aan de onderkant om je schoenen los op te bergen. Schouderbanden met vulling en een borstband zorgen dat je je gear comfortabel mee kunt nemen.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/vqv5wvgxyyzitaapvb4h/jordan-velocity-rugzak-W2CQcr.jpg', 'heren', 'accessoires'),
('Nike Shield JDI Flash', 'De Nike Shield JDI Flash handschoenen houden wind en water buiten zodat je droog en warm blijft. Door de siliconen en het materiaal op de vingers kun je je telefoon tijdens het rennen makkelijk gebruiken.', 'https://c.static-nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/m3rxey5gmqdmtgylbfg1/shield-jdi-flash-hardloophandschoenen-heren-4825ZQ.jpg', 'heren', 'accessoires'),
('Nike 710 ml SS HyperCharge Straw', 'De Nike 710 ml SS HyperCharge Straw bidon is gemaakt van duurzaam, geïsoleerd roestvrij staal om je drankjes koel te houden. Door de innovatieve schuifknop kun je de bidon met één hand openen, zodat je onderweg makkelijk kunt drinken.', 'https://images.nike.com/is/image/DotCom/PDP_HERO/NOBG0_613_A/710-ml-ss-hypercharge-straw-bidon.jpg', 'heren', 'accessoires'),
('Nike AF1', 'De Nike AF1 draagtas geeft de AF1 inspiratie bloot met een dubbel handvat van touw en een graphic die voor een opvallende look zorgt. Gebruik de handige clip om sleutels, bidons en andere kleine voorwerpen makkelijk te bevestigen. Je kunt je computer opbergen in de laptopsleeve aan de binnenkant.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/dj75fs60iy0btu5hiok0/af1-draagtas-xC9BLQ.jpg', 'dames', 'accessoires'),
('Nike Heritage 2.0', 'De Nike Heritage 2.0 rugzak combineert stijl en functionaliteit door middel van een opvallende print en een strak design. De gewatteerde schouderbanden zorgen ervoor dat je comfortabel je spullen kunt dragen.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/lhzpm15sdn0aty957hnc/heritage-2-rugzak-h2pzbW.jpg', 'dames', 'accessoires'),
('Nike Heritage', 'Dankzij een tweekleurige, geruite print zorgt de Nike Heritage heuptas voor twee keer zoveel stijl. De tas heeft een verstelbare heupband en twee ritsvakken zodat je gemakkelijk bij je spullen kunt terwijl je door de stad loopt.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/qgyxso2u6nhsje0lvuz4/heritage-heuptas-tDvZSc.jpg', 'dames', 'accessoires'),
('Nike Revere', 'De Nike Revere zonnebril is licht en comfortabel en geeft je een heel nieuwe look met z\'n metalen accenten en z\'n glanzende, moderne design.', 'https://c.static-nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/sqmtms9b9sgwmmdmpqis/revere-zonnebril-68T59z.jpg', 'dames', 'accessoires'),
('Nike Radiate', 'De Nike Radiate rugzak heeft een bovenklep en meerdere vakken om spullen veilig in op te bergen. Een laptopsleeve biedt gewatteerde bescherming.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/r7fmjbk7nl9mwwvaqpux/radiate-trainingsrugzak-dames-Jvkbmv.jpg', 'dames', 'accessoires'),
('Nike Radiate', 'De Nike Radiate tas heeft een hoofdvak met rits en een binnenvak voor je belangrijkste spullen. Het duurzame design omvat een afneembare schouderband voor draagcomfort op maat wanneer je van kantoor naar de sportschool loopt.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/swyhnvnmbrxitztifztk/radiate-trainingstas-dames-wJfVbT.jpg', 'dames', 'accessoires'),
('Nike AeroBill Tailwind', 'Maak je look helemaal af met de Nike AeroBill Tailwind hardlooppet. Mesh vlakken zorgen voor ventilatie en een licht gevoel en het vochtafvoerende materiaal houdt je comfortabel.', 'https://c.static-nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/ey4wsvbvl1nzuvylj6uu/aerobill-tailwind-hardlooppet-QCwPDD.jpg', 'dames', 'accessoires'),
('Nike', 'De Nike heuptas heeft een smal, licht design en een elastische, verstelbare riem die stevig om je taille zit.', 'https://c.static-nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/kdrs6sodz1piknukjnsh/smalle-heuptas-vHfnvg.jpg', 'dames', 'accessoires'),
('Nike Revere Mirrored', 'De Nike Revere Mirrored zonnebril is licht en comfortabel en geeft je een heel nieuwe look met z\'n metalen accenten en z\'n glanzende, moderne design.', 'https://c.static-nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/u6sxukltfvykozeiyl18/revere-mirrored-zonnebril-Q1dtbG.jpg', 'dames', 'accessoires'),
('Nike AF1', 'De Nike AF1 draagtas heeft een op AF1 geïnspireerde stijl met een handvat van touw en overal kettinglusjes. In de binnenvakken met rits en de laptopsleeve kun je je spullen veilig opbergen. Het materiaal met paisleyprint zorgt voor een gave streetlook.', 'https://c.static-nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/rharkuqdvahrllyyoxcp/af1-draagtas-4xLkpQ.jpg', 'dames', 'accessoires');
COMMIT;


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
